package uk.gov.hmrc.perftests.requests

import uk.gov.hmrc.performance.simulation.PerformanceTestRunner
import uk.gov.hmrc.perftests.requests.ADDERRequst._
import uk.gov.hmrc.perftests.requests.Requests._

class Simulation extends PerformanceTestRunner {

  setup("Sdes Journey", "Navigate to sdes  page") withRequests (
    getLoginPage,
    postStrideAuthPage,
    postSamlResponse,
    getSdesLandingPage,
    getRequestDatamovement,
    getCreateDER,
    getCreateTitlename,
    postEnterDataMovementName,
    getHowDataMoved,
    postDigitaltransfer,
    getDirection,
    postDirection,
    getBusinessArea,
    postDERDirection,
    getTemplate,
    postInformationType,
    getmovingdata,
    postFrequency,
      getFrequency,
    postDailyFrequency,
      getRequestReviewed,
    postRequestSendingDate,
      getDataContentType,
      postContentType,
      getContentIdentify,
      postIndentify,
      getSpecialCustomer,
      postSpecialCustomer,
      getClassification,
      postClassification,
      getDataNeeded,
      postDataNeeded,
      getRequestors,
      postAddTeammember,
//    postAdditionalTeamMember,
      getOrganisationPage,
      postAddOrganisation,
      getIndentifiers,
      postIndentifiers,
      getAdditionalInfo,
      postAdditonalInformation,
      getCYAPage,
      postSubmitDER
  )

  setup("ADDer Journey", "Navigate to AD DER page") withRequests   (
    getLoginPage,
    postStrideAuthPage,
    postSamlResponse,
    getSdesLandingPage,
    getRequestDatamovement,
    getCreateDER,
    getCreateTitlename,
    postEnterDataMovementName,
    getHowDataMoved,
    postPhysicaltransfer,
    getSteps,
    postStepstomoveData,
      getDataProtected,
      postProtectedYes,
      getmovingdata,
      postFrequency,
        getFrequency,
    postPhysicalDailyFrequency,
        getStartdate,
        postStartDate,
          getRequestReviewed,
          postRequestSendingDate,
          getDataContentType,
          postContentType,
          getContentIdentify,
          postIndentify,
          getSpecialCustomer,
          postSpecialCustomer,
          getClassification,
          postSecurityClassification,
          getApprovalgroup,
          postApprovalgroup,
          getDataNeeded,
          postDataNeeded,
          getRequestors,
    postAddTeammember,
//         postAdditionalTeamMember,
          getDatafrom,
          postDataFrom,
          getDataTo,
          postDataTo,
          getAdditionalInfo,
    postPhysicalDERAdditonalInformation,
    getPhysicalCYAPage,
    postPhysicalDERSubmit,
  )

  runSimulation()
}
